[package]
name = "spatiand-hmd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
glam.workspace = true
thiserror.workspace = true
serde.workspace = true
toml.workspace = true
log.workspace = true
libc = "0.2"

[dev-dependencies]
env_logger.workspace = true
